version: 1
disable_existing_loggers: no  # 是否覆蓋以前的配置logger
formatters:
        simple:
            format: "%(name)s - %(levelname)s - %(message)s"
        save:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S"

root: #默認情況下配置
    level: DEBUG
    handlers: [console]

loggers: #如果有設定loggers的話會採用，否則採用root設定
    main:
            level: DEBUG
            handlers: [console, error_file_handler]
            propagate: no

#    my_module2:
#            level: DEBUG
#            handlers: [console, info_file_handler]
#            propagate: yes

handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout

    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: WARNING
            formatter: save
            filename: .\logs\errors.log
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8

#    info_file_handler:
#            class: logging.handlers.RotatingFileHandler
#            level: INFO
#            formatter: simple
#            filename: .\logs\debug.log
#            maxBytes: 5242880
#            backupCount: 1
#            encoding: utf8
